### ISSUE TITLE
Fix missing extension on v1.1.1

### ISSUE THREAD

**Issue by carlopi** [duckdb/community-extensions#127]
Tuesday we released `v1.1.1`, and most extensions have been built / tested and deployed already.

I am aware of 3 cases that are not working out of the box while changing the DuckDB version:
* bigquery (@hafenkran) failed a Linux CI run: https://github.com/duckdb/community-extensions/actions/runs/10994446572, this likely requires minor modifications on our side
* duckpgq (@Dtenwolde), see https://github.com/duckdb/community-extensions/pull/126
* shellfs (@rustyconover) depends on `python` being available when tests are run (see https://github.com/duckdb/community-extensions/actions/runs/10973205947/job/30470361697). This requires minor modification on our side.

Those looks to be all on our side, I will update as they are fixed.

**Comment by carlopi** [comment]
`shellfs` has been published. 2 to go.

`duckpgq` needs minor changes to the code to be compatible, see comment here: https://github.com/duckdb/community-extensions/pull/126#issuecomment-2387828556

`bigquery` is the most complex one since we are running in some problems with disk space within the container that builds the extension. I am not sure what can be done on our side, I think `docker` should alreay be using all available memory but not sure. As a short term solution it would be viable to skip building for `linux_arm_gcc4`, and in parallel iterate on this extension side?

**Comment by hafenkran** [comment]
Hey @carlopi 

I took some time today to look into your workflow and the issue with building the BigQuery extension. I noticed that the disk space on the worker nodes seems to be the main bottleneck. It usually hovers around 21GB per machine, which fills up pretty quickly for the build.

From my perspective, a lot of unnecessary stuff comes pre-installed on these worker nodes. Since you're now shifting to a Docker-based build, I believe there's some potential for optimization on your side. Here are some suggestions: 

1. **Optimizing the Dockerfile**: I noticed the Dockerfile you're using ca be slightly optimized. I spent a bit of time working on it and managed to cut down the size of the gcc4 image significantly. For the other images, I was able to reduce image sizes by 25-30%. I'd be happy to share my version if you're interested. 
![mega-optimized](https://github.com/user-attachments/assets/2db03540-b6f5-4569-be78-e7008a453671)

2. **Clearing some pre-installed tools**: There's quite a bit of bloatware on the worker nodes (with over 50GB already used out of the 73GB available). For example, I found some pre-installed docker images taking up quite some space and various tools (like node, go, etc.) in the `/opt/hostedtoolcache` folder that sums up to around 12-13GB. I think in your docker build you don't need these. I just added a step in my workflow that deletes these unnecessary docker images and files at the start of the build process (see [here](https://github.com/hafenkran/duckdb-bigquery/blob/b0ad92f85596c3f2ba5d9fece023c32127cef3d4/.github/workflows/_extension_distribution.yml#L196)). 

pre-installed docker images
![pre-installed-images](https://github.com/user-attachments/assets/572cda1c-3271-48f0-8edf-7c5eee3ef469)

before the delete
![cleanup-before](https://github.com/user-attachments/assets/a291b006-6d5d-467b-8329-1bd4860690c9)

after the delete
![cleanup-after](https://github.com/user-attachments/assets/db2ba8f2-94c9-42b1-be83-4631a50d98b3)

3. **Using existing Github Actions for space management**: Alternatively to option 2, there are also a few GH Actions that allow you to configure and reduce the disk usage even further (e.g., [here](https://github.com/marketplace/actions/free-disk-space-ubuntu)). While the option above is straightforward, you could explore these actions for more advanced disk management if needed. 

Let me know what you think!

**Comment by Dtenwolde** [comment]
DuckPGQ has now also been updated https://github.com/duckdb/community-extensions/pull/135

**Comment by carlopi** [comment]
And https://github.com/duckdb/community-extensions/pull/136 should solve `bigquery`, and we should be good to close this!
