### ISSUE TITLE
is community extensions down?

### ISSUE THREAD

**Issue by rapatel0** [duckdb/community-extensions#215]
I was trying to load extensions onto a new machine and I couldn't. 

Checked the extension domain against global dns and it doesn't resolve. 

`community-extensions.duckdb.org`

<img width="941" alt="image" src="https://github.com/user-attachments/assets/83a9f8b7-1dc0-4ccf-9dbc-54f8bf36c47c">

**Comment by carlopi** [comment]
Thanks, I do reproduce, I will look at this.

**Comment by samansmink** [comment]
is up again, thanks for reporting!

**Comment by carlopi** [comment]
This should be back up online, barred some transient cached failures.

Github action job that installs community extensions looks now to be functional: https://github.com/duckdb/duckdb-web/actions/runs/12145731330/job/33868029659.

(while same job did fail 22 minutes ago due to failure)
Sorry for the outage.
