### ISSUE TITLE
Failing extension deploys - Error: Unable to find any artifacts for the associated workflow

### ISSUE THREAD

**Issue by archiewood** [duckdb/community-extensions#243]
We're encountering an issue whereby the extension CI process fails to deploy the binaries after a successful build.

https://github.com/evidence-dev/duckdb_gsheets/pull/48

Specifically the error being thrown is 

```
0s
Run actions/download-artifact@v3
  with:
    name: gsheets-v[1](https://github.com/evidence-dev/duckdb_gsheets/actions/runs/12548878003/job/34989862992?pr=48#step:4:1).1.3-extension-linux_amd64
    path: /tmp/extension
  
Starting download for gsheets-v1.1.[3](https://github.com/evidence-dev/duckdb_gsheets/actions/runs/12548878003/job/34989862992?pr=48#step:4:3)-extension-linux_amd64
Error: Unable to find any artifacts for the associated workflow
```

**Comment by samansmink** [comment]
The artifact upload step is using v4 whereas the download step is on v3 because that is checked into the extension repo and has fallen behind.

You can probably consider removing the local deploy workflow as we have done recently in the extension template https://github.com/duckdb/extension-template/pull/98
